name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install live-server and wait-on
        run: npm install -g live-server wait-on

      - name: Start live-server and run tests
        run: |
          live-server . --port=8080 --quiet &
          npx wait-on http://127.0.0.1:8080/source/frontend/DailySpreadPage/dailyspread.html
          sleep 5
          npx jest --config=jest.e2e.config.js
