name: Run Puppeteer E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start local server
        run: |
          npx live-server source --port=8080 --quiet &
          sleep 5

      - name: Run E2E Tests
        run: npm run test:e2e
