name: Generate JSDoc

on:
  push:
    branches: [main]
    paths:
    - '**/*.js'
  pull_request:
    branches: [main]
    paths:
    - '**/*.js'

jobs:
  jsdoc:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3

      - 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - 
        run: npm install

      - 
        run: npm run docs
