name: "Minify Assets"

on:
  pull_request:
    branches: [main]
    paths:
      - 'source/frontend/**/*.css'
      - 'source/frontend/**/*.html'
      - 'source/frontend/**/*.js'
  push:
    branches: [main]
    paths:
      - 'source/frontend/**/*.css'
      - 'source/frontend/**/*.html'
      - 'source/frontend/**/*.js'

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Minify CSS with cssnano
        uses: samuelmeuli/action-cssnano@v2
        with:
          files: 'source/frontend/**/*.css'

      - name: Minify HTML
        uses: crazy-max/ghaction-html-minifier@v1
        with:
          files: 'source/frontend/**/*.html'
          options: >
            --collapse-whitespace
            --remove-comments

      - name: Minify JS with UglifyJS
        uses: uglifyjs/uglifyjs-action@v1
        with:
          files: 'source/frontend/**/*.js'
          options: '-c -m'